### PR TITLE
Integration testing

### PR DESCRIPTION
**Pull request by samuelstevens**
Some more robust integration testing. Currently, it checks that:
* an instance of the app will start
* queries will return some songs
* filtering via GET requests actually changes the songs that come back

Still needs testing:
* Javascript (maybe not relevant for a project this size)
* The Spotify playlist button (not sure how to test that the Spotify playlist contains the correct songs)

`make coverage` will create and show an HTML report of what statements need further testing.

### CODE REVIEW

**Review by ritachitsark — COMMENTED** [review]
We can test the playlist feature by checking the test albums on Spotify ourselves and then hardcoding the songs of those albums in an integration test. The PR looks good but I'll wait for someone else to look at it as well before I approve it

**Review by Alex7Li — CHANGES_REQUESTED** [review]
I'm not sure how you are doing these tests, before I was making tests using python's unittest framework (wrap a lot of functions in a class that extends unittest.TestCase and add a main method, you can look in test/spotify.py for an example). To run that you can just type python -m unittest. Clearly you are doing sometime different here but we should be consistent. How are you creating your tests, we should be consistent and either change your tests or my old ones.

I wouldn't worry about testing that the spotify songs are right, we can make tests for that on the spotify side.

Overall it looks good though

**Comment by samuelstevens** [comment]
> I'm not sure how you are doing these tests, before I was making tests using python's unittest framework (wrap a lot of functions in a class that extends unittest.TestCase and add a main method, you can look in test/spotify.py for an example). To run that you can just type python -m unittest. Clearly you are doing sometime different here but we should be consistent. How are you creating your tests, we should be consistent and either change your tests or my old ones.

I'm using pytest because that's what flask recommends for setup/teardown between tests (setting up clients, servers, etc). I'll update your tests to work with pytest.

**Review by Alex7Li — APPROVED** [review]
Looks good, thanks for fixing our tests

**Pull request merged**
